import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.concurrent.ExecutionException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;


/**
 * Main GUI Frame for the Course Scheduler application.
 * Handles user interactions and displays data.
 * Uses SwingWorker for background database operations.
 *
 * @author acv (Original)
 * @author Gemini (Refactored)
 */
public class MainFrame extends JFrame { // Inherit directly from JFrame

    // --- Constants ---
    private static final String AUTHOR_FILE = "scheduler_config.txt"; // Use a more descriptive name
    private static final String[] SCHEDULE_TABLE_HEADERS = {"Course Code", "Status"};
    private static final String[] CLASS_TABLE_HEADERS = {"Course Code", "Description", "Seats"};
    private static final String[] STUDENT_TABLE_HEADERS = {"Student Name", "Status"}; // For display students in class
    // FIXED: Removed duplicate STUDENT_TABLE_HEADERS definition

    // --- Instance Variables ---
    private String currentSemester;
    private String author;
    private String project;

    // --- UI Components ---
    // NOTE: Core components like jTabbedPane1, jPanel1, etc., and the
    //       components in the 'Add Semester' tab are declared and initialized
    //       by the NetBeans generated `initComponents()` method below.
    //       The variables declared here are for components added *manually*
    //       in the `setupCustomComponents` and `initializeXxxPanel` methods.

    // Components declared in initComponents() are listed at the bottom

    // Admin - Add Course Panel Components (jPanel4)
    private JPanel jPanel4; // Panel reference (will point to jPanel4_placeholder's container)
    private JTextField courseCodeTextField;
    private JTextField courseDescTextField;
    private JButton addCourseButton;
    private JLabel courseStatusLabel; // Feedback label

    // Admin - Add Class Panel Components (jPanel6)
    private JPanel jPanel6; // Panel reference
    private JComboBox<String> addClassCourseComboBox; // Separate combo box for this panel
    private JTextField seatsTextField;
    private JButton addClassButton;
    private JLabel classStatusLabel; // Feedback label

    // Admin - Add Student Panel Components (jPanel7)
    private JPanel jPanel7; // Panel reference
    private JTextField studentIdTextField;
    private JTextField firstNameTextField;
    private JTextField lastNameTextField;
    private JButton addStudentButton;
    private JLabel studentStatusLabel; // Feedback label

    
    // Admin - Display/Drop Controls (Added to jPanel1 SOUTH)
    private JPanel adminControlPanel;
    private JComboBox<String> adminClassComboBox; // Combo box for selecting class to view/drop
    private JButton adminDisplayStudentsButton;
    private JButton adminDropClassButton;
    private JComboBox<String> adminStudentComboBox; // Combo box for selecting student to drop
    private JButton adminDropStudentButton;
    private JLabel adminStatusLabel; // Feedback for admin drop actions

    // Student Tab Panel Components (jPanel2)
    private JPanel studentControlPanel; // Top panel with combo boxes and buttons
    private JComboBox<String> studentSelectStudentComboBox; // Combo box for student selection
    private JComboBox<String> studentSelectClassComboBox; // Combo box for class selection
    private JButton scheduleButton;
    private JButton displayScheduleButton;
    private JButton displayClassesButton; // Button to display all classes for the semester
    private JButton studentDropClassButton; // Button for student to drop a class
    private JLabel studentScheduleStatusLabel; // Feedback label
    private JTable displayTable;
    private JScrollPane tableScrollPane;


    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        checkData(); // Load author info first
        initComponents(); // Initialize Swing components generated by NetBeans/GUI builder
        setupCustomComponents(); // Setup components not handled by initComponents
        
        // Initialize database tables if needed
        try {
            DBInitializer.initializeDatabase();
            loadInitialData(); // Load semesters, courses, students into combo boxes
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Database initialization failed: " + e.getMessage(), 
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
            System.err.println("Database initialization failed:");
            e.printStackTrace();
        }
        
        setupWindowListener(); // Add listener to close DB connection on exit
    }

    // --- Initialization Methods ---

    /**
     * Sets up components and layouts not managed by the NetBeans GUI builder's
     * generated initComponents(). This includes panels added dynamically and
     * event listeners.
     */
    private void setupCustomComponents() {
        setTitle("Course Scheduler by " + author); // Set window title

        // Initialize panel references by getting the placeholder components from the tabbed pane
        // NOTE: Assumes the tab order in initComponents() is preserved:
        // 0: Add Semester, 1: Add Course, 2: Add Class, 3: Add Student
        jPanel4 = (JPanel) jTabbedPane2.getComponentAt(1); // Get the JPanel container for the "Add Course" tab
        jPanel6 = (JPanel) jTabbedPane2.getComponentAt(2); // Get the JPanel container for the "Add Class" tab
        jPanel7 = (JPanel) jTabbedPane2.getComponentAt(3); // Get the JPanel container for the "Add Student" tab

        // Clear placeholder content and setup layouts/components for dynamic panels
        jPanel4.removeAll(); // Remove any default content from the placeholder
        initializeAddCoursePanel(jPanel4);
        jPanel6.removeAll();
        initializeAddClassPanel(jPanel6);
        jPanel7.removeAll();
        initializeAddStudentPanel(jPanel7);

        // Setup the student tab panel (jPanel2)
        jPanel2.removeAll();
        initializeStudentPanel(jPanel2);

        // Setup the admin display/drop controls area (added below the admin tabs in jPanel1)
        initializeAdminControls(jPanel1); // jPanel1 is the main Admin tab panel

        // Add Action Listeners (using lambda expressions for brevity)
        aboutButton.addActionListener(e -> aboutButtonActionPerformed());
        addSemesterSubmitButton.addActionListener(e -> addSemesterSubmitButtonActionPerformed());
        changeSemesterButton.addActionListener(e -> changeSemesterButtonActionPerformed());

        // Listeners for buttons that trigger background tasks
        addCourseButton.addActionListener(e -> addCourseButtonActionPerformed());
        addClassButton.addActionListener(e -> addClassButtonActionPerformed());
        addStudentButton.addActionListener(e -> addStudentButtonActionPerformed());
        scheduleButton.addActionListener(e -> scheduleClassButtonActionPerformed());
        displayScheduleButton.addActionListener(e -> displayScheduleButtonActionPerformed());
        displayClassesButton.addActionListener(e -> displayClassesButtonActionPerformed());
        studentDropClassButton.addActionListener(e -> studentDropClassButtonActionPerformed());
        adminDisplayStudentsButton.addActionListener(e -> adminDisplayStudentsButtonActionPerformed());
        adminDropClassButton.addActionListener(e -> adminDropClassButtonActionPerformed());
        adminDropStudentButton.addActionListener(e -> adminDropStudentButtonActionPerformed());
        // Initial population of combo boxes depends on semester being set first
    }

    /**
     * Loads initial data like semesters, courses, and students into combo boxes.
     * Handles potential SQLExceptions during data loading.
     */
    private void loadInitialData() {
        rebuildSemesterComboBoxes(); // Load semesters first

        // Subsequent loads depend on semester being selected successfully
        // These are triggered within rebuildSemesterComboBoxes' done() method
        // and updateCurrentSemester().
        // rebuildCourseComboBoxes(); // Called by updateCurrentSemester
        rebuildStudentComboBoxes(); // Load students (doesn't depend on semester)
    }

    /**
     * Adds a WindowListener to ensure the database connection is closed
     * when the application window is closed.
     */
    private void setupWindowListener() {
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.out.println("Closing application, closing DB connection...");
                DBConnection.closeConnection();
                super.windowClosing(e); // FIXED: Call super method
            }
        });
    }


    /**
     * Initializes the Add Course panel (jPanel4).
     * @param panel The JPanel to add components to.
     */
    private void initializeAddCoursePanel(JPanel panel) {
        panel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = createGBC(); // Helper for constraints

        // Course Code
        panel.add(new JLabel("Course Code:"), gbc);
        courseCodeTextField = new JTextField(20);
        gbc.gridx = 1;
        gbc.weightx = 1.0; // Allow text field to grow horizontally
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(courseCodeTextField, gbc);

        // Description
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.0; // Reset weight
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.EAST; // Align label right
        panel.add(new JLabel("Description:"), gbc);
        courseDescTextField = new JTextField(20);
        gbc.gridx = 1;
        gbc.weightx = 1.0; // Allow text field to grow
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST; // Align field left
        panel.add(courseDescTextField, gbc);

        // Add Button
        addCourseButton = new JButton("Add Course");
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 0.0; // No horizontal stretch for button
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.WEST; // Align button left
        panel.add(addCourseButton, gbc);

        // Status Label
        courseStatusLabel = new JLabel(" "); // Initial empty status
        gbc.gridy = 3;
        gbc.gridwidth = 2; // Span across both columns
        panel.add(courseStatusLabel, gbc);

        panel.revalidate(); // Ensure layout changes are applied
        panel.repaint();
    }

    /**
     * Initializes the Add Class panel (jPanel6).
     * @param panel The JPanel to add components to.
     */
    private void initializeAddClassPanel(JPanel panel) {
        panel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = createGBC();

        // Course ComboBox
        panel.add(new JLabel("Select Course:"), gbc);
        addClassCourseComboBox = new JComboBox<>(); // Initialize here
        gbc.gridx = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(addClassCourseComboBox, gbc);

        // Seats TextField
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.0;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.EAST;
        panel.add(new JLabel("Number of Seats:"), gbc);
        seatsTextField = new JTextField(10); // Smaller field for seats
        gbc.gridx = 1;
        gbc.weightx = 0.0; // Don't stretch seat field excessively
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(seatsTextField, gbc);

        // Add Button
        addClassButton = new JButton("Add Class");
        gbc.gridy = 2;
        panel.add(addClassButton, gbc);

        // Status Label
        classStatusLabel = new JLabel(" ");
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        panel.add(classStatusLabel, gbc);

        panel.revalidate();
        panel.repaint();
    }

    /**
     * Initializes the Add Student panel (jPanel7).
     * @param panel The JPanel to add components to.
     */
    private void initializeAddStudentPanel(JPanel panel) {
        panel.setLayout(new GridBagLayout());
        GridBagConstraints gbc = createGBC();

        // Student ID
        panel.add(new JLabel("Student ID:"), gbc);
        studentIdTextField = new JTextField(20);
        gbc.gridx = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel.add(studentIdTextField, gbc);

        // First Name
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.0;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.EAST;
        panel.add(new JLabel("First Name:"), gbc);
        firstNameTextField = new JTextField(20);
        gbc.gridx = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(firstNameTextField, gbc);

        // Last Name
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.0;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.EAST;
        panel.add(new JLabel("Last Name:"), gbc);
        lastNameTextField = new JTextField(20);
        gbc.gridx = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(lastNameTextField, gbc);

        // Add Button
        addStudentButton = new JButton("Add Student");
        gbc.gridy = 3;
        gbc.weightx = 0.0;
        gbc.fill = GridBagConstraints.NONE;
        panel.add(addStudentButton, gbc);

        // Status Label
        studentStatusLabel = new JLabel(" ");
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        panel.add(studentStatusLabel, gbc);

        panel.revalidate();
        panel.repaint();
    }

     /**
     * Initializes the Student interaction panel (jPanel2).
      * @param panel The JPanel to add components to.
     */
    private void initializeStudentPanel(JPanel panel) {
        panel.setLayout(new BorderLayout()); // Use BorderLayout for overall structure

        // Control Panel at the top (NORTH)
        studentControlPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = createGBC();

        // Student Selection
        studentControlPanel.add(new JLabel("Select Student:"), gbc);
        studentSelectStudentComboBox = new JComboBox<>();
        gbc.gridx = 1;
        gbc.weightx = 0.5; // Give some weight
        gbc.fill = GridBagConstraints.HORIZONTAL;
        studentControlPanel.add(studentSelectStudentComboBox, gbc);

        // Class Selection
        gbc.gridx = 2;
        gbc.weightx = 0.0; // Reset weight
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.EAST;
        studentControlPanel.add(new JLabel("Select Class:"), gbc);
        studentSelectClassComboBox = new JComboBox<>();
        gbc.gridx = 3;
        gbc.weightx = 0.5; // Give some weight
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;
        studentControlPanel.add(studentSelectClassComboBox, gbc);

        // Buttons (Second Row in GridBagLayout)
        scheduleButton = new JButton("Schedule Class");
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.0;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.CENTER; // Center buttons
        studentControlPanel.add(scheduleButton, gbc);

        displayScheduleButton = new JButton("Display Schedule");
        gbc.gridx = 1;
        studentControlPanel.add(displayScheduleButton, gbc);

        displayClassesButton = new JButton("Display All Classes");
        gbc.gridx = 2;
        studentControlPanel.add(displayClassesButton, gbc);

        studentDropClassButton = new JButton("Drop Selected Class");
        gbc.gridx = 3;
        studentControlPanel.add(studentDropClassButton, gbc);

        // Status Label (Third Row)
        studentScheduleStatusLabel = new JLabel(" ");
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 4; // Span across all columns
        gbc.fill = GridBagConstraints.HORIZONTAL;
        studentControlPanel.add(studentScheduleStatusLabel, gbc);

        // Table in the center (CENTER)
        displayTable = new JTable();
        // Set default empty model initially
        displayTable.setModel(new DefaultTableModel(new Object[][]{}, SCHEDULE_TABLE_HEADERS));
        tableScrollPane = new JScrollPane(displayTable);

        panel.add(studentControlPanel, BorderLayout.NORTH);
        panel.add(tableScrollPane, BorderLayout.CENTER);

        panel.revalidate();
        panel.repaint();
    }

     /**
     * Initializes the Admin control panel for displaying/dropping students/classes.
     * Adds this panel to the SOUTH region of the main Admin panel (jPanel1).
      * @param adminPanel The main admin JPanel (jPanel1) to add the controls to.
     */
    private void initializeAdminControls(JPanel adminPanel) {
        // NOTE: jPanel1 already uses BorderLayout, set by initComponents()

        // The main tabbed pane (jTabbedPane2) goes in the CENTER (already added by initComponents)
        // We add the new control panel to the SOUTH

        // New panel for the bottom controls
        adminControlPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = createGBC();

        // --- Row 0: Class Controls ---
        adminControlPanel.add(new JLabel("Select Class:"), gbc);
        adminClassComboBox = new JComboBox<>(); // Combo box for class selection
        gbc.gridx = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        adminControlPanel.add(adminClassComboBox, gbc);

        adminDisplayStudentsButton = new JButton("Display Students in Class");
        gbc.gridx = 2;
        gbc.weightx = 0.0;
        gbc.fill = GridBagConstraints.NONE;
        adminControlPanel.add(adminDisplayStudentsButton, gbc);

        adminDropClassButton = new JButton("Drop Class");
        gbc.gridx = 3;
        adminControlPanel.add(adminDropClassButton, gbc);

        // --- Row 1: Student Controls ---
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.0;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.EAST;
        adminControlPanel.add(new JLabel("Select Student:"), gbc);

        adminStudentComboBox = new JComboBox<>(); // Combo box for student selection
        gbc.gridx = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.WEST;
        adminControlPanel.add(adminStudentComboBox, gbc);

        adminDropStudentButton = new JButton("Drop Student");
        gbc.gridx = 2;
        gbc.gridwidth = 2; // Span remaining columns
        gbc.weightx = 0.0;
        gbc.fill = GridBagConstraints.NONE;
        gbc.anchor = GridBagConstraints.WEST; // Align left
        adminControlPanel.add(adminDropStudentButton, gbc);

        // --- Row 2: Status Label ---
        adminStatusLabel = new JLabel(" ");
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 4; // Span all columns
        gbc.fill = GridBagConstraints.HORIZONTAL;
        adminControlPanel.add(adminStatusLabel, gbc);

        // Add the control panel to the SOUTH of the main admin panel (jPanel1)
        adminPanel.add(adminControlPanel, BorderLayout.SOUTH);

        adminPanel.revalidate();
        adminPanel.repaint();
    }


    // --- Data Loading and UI Update Methods ---

    /**
     * Fetches the semester list from the database and updates the
     * semester combo boxes and current semester label.
     */
    public void rebuildSemesterComboBoxes() {
        // Use SwingWorker to fetch semesters in the background
        new SwingWorker<ArrayList<String>, Void>() {
            @Override
            protected ArrayList<String> doInBackground() throws Exception {
                return SemesterQueries.getSemesterList();
            }

            @Override
            protected void done() {
                try {
                    ArrayList<String> semesters = get();
                    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(semesters.toArray(new String[0]));
                    currentSemesterComboBox.setModel(model);

                    if (!semesters.isEmpty()) {
                        // Set current semester to the first in the list by default
                        String firstSemester = semesters.get(0);
                        currentSemesterComboBox.setSelectedItem(firstSemester); // Select in combo box
                        updateCurrentSemester(firstSemester); // Update label and trigger dependent updates
                    } else {
                        updateCurrentSemester("None"); // Indicate no semesters
                        // Disable relevant controls if no semester is available
                        // (Handled within updateCurrentSemester)
                    }
                } catch (InterruptedException | ExecutionException e) {
                    handleDatabaseError(e, "loading semesters");
                    updateCurrentSemester("Error");
                    // Disabling controls handled by updateCurrentSemester
                }
            }
        }.execute();
    }

    /**
     * Fetches course codes (all or by semester) and updates relevant combo boxes.
     */
    private void rebuildCourseComboBoxes() {
        if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
            // Clear or disable course combo boxes if no valid semester is selected
             DefaultComboBoxModel<String> emptyModel = new DefaultComboBoxModel<>();
             addClassCourseComboBox.setModel(emptyModel);
             studentSelectClassComboBox.setModel(emptyModel);
             adminClassComboBox.setModel(emptyModel);
             return;
        }

        // Fetch all courses for the "Add Class" panel's combo box
        new SwingWorker<ArrayList<String>, Void>() {
            @Override
            protected ArrayList<String> doInBackground() throws Exception {
                return SemesterQueries.getAllCourseCodes();
            }

            @Override
            protected void done() {
                try {
                    ArrayList<String> courses = get();
                    addClassCourseComboBox.setModel(new DefaultComboBoxModel<>(courses.toArray(new String[0])));
                } catch (InterruptedException | ExecutionException e) {
                     handleDatabaseError(e, "loading all courses");
                     addClassCourseComboBox.setModel(new DefaultComboBoxModel<>(new String[]{"Error loading..."}));
                }
            }
        }.execute();

        // Fetch courses specific to the current semester for Student and Admin panels
        new SwingWorker<ArrayList<String>, Void>() {
             @Override
             protected ArrayList<String> doInBackground() throws Exception {
                  return SemesterQueries.getAllCourseCodesBySemester(currentSemester);
             }

             @Override
             protected void done() {
                  try {
                       ArrayList<String> semesterCourses = get();
                       DefaultComboBoxModel<String> semesterCourseModelStudent = new DefaultComboBoxModel<>(semesterCourses.toArray(new String[0]));
                       DefaultComboBoxModel<String> semesterCourseModelAdmin = new DefaultComboBoxModel<>(semesterCourses.toArray(new String[0])); // Need separate model instance
                       // Update both student and admin class selection combo boxes
                       studentSelectClassComboBox.setModel(semesterCourseModelStudent);
                       adminClassComboBox.setModel(semesterCourseModelAdmin);
                  } catch (InterruptedException | ExecutionException e) {
                       handleDatabaseError(e, "loading courses for semester " + currentSemester);
                       DefaultComboBoxModel<String> errorModel = new DefaultComboBoxModel<>(new String[]{"Error loading..."});
                       studentSelectClassComboBox.setModel(errorModel);
                       adminClassComboBox.setModel(new DefaultComboBoxModel<>(new String[]{"Error loading..."})); // Separate instance
                  }
             }
         }.execute();
    }


    /**
     * Fetches the student list and updates student selection combo boxes.
     * If the list is empty, shows a helpful message to add students first.
     */
    private void rebuildStudentComboBoxes() {
         new SwingWorker<ArrayList<String>, Void>() {
            @Override
            protected ArrayList<String> doInBackground() throws Exception {
                return SemesterQueries.getAllStudents();
            }

            @Override
            protected void done() {
                try {
                    ArrayList<String> students = get();

                    boolean hasRealStudents = !students.isEmpty();

                    // Handle empty student list with descriptive message
                    if (!hasRealStudents) {
                        students.add("No students found - add students first");
                    }

                    DefaultComboBoxModel<String> studentModel = new DefaultComboBoxModel<>(students.toArray(new String[0]));
                    // Update both student and admin student selection combo boxes
                    studentSelectStudentComboBox.setModel(studentModel);
                    // Use a separate model instance for the admin combo box
                    adminStudentComboBox.setModel(new DefaultComboBoxModel<>(students.toArray(new String[0])));

                    // Enable/disable student-specific buttons based ONLY on whether real students exist
                    // Semester-based enabling/disabling is handled separately in updateCurrentSemester
                    scheduleButton.setEnabled(hasRealStudents);
                    displayScheduleButton.setEnabled(hasRealStudents);
                    studentDropClassButton.setEnabled(hasRealStudents);
                    adminDropStudentButton.setEnabled(hasRealStudents);


                } catch (InterruptedException | ExecutionException e) {
                    handleDatabaseError(e, "loading students");
                    DefaultComboBoxModel<String> errorModel = new DefaultComboBoxModel<>(new String[]{"Error loading..."});
                    studentSelectStudentComboBox.setModel(errorModel);
                    adminStudentComboBox.setModel(new DefaultComboBoxModel<>(new String[]{"Error loading..."})); // Separate instance
                    // Disable buttons on error
                    scheduleButton.setEnabled(false);
                    displayScheduleButton.setEnabled(false);
                    studentDropClassButton.setEnabled(false);
                    adminDropStudentButton.setEnabled(false);
                }
            }
        }.execute();
    }

    /**
    * Updates the current semester label and triggers updates for dependent UI elements.
    * @param newSemester The new semester name ("None" or "Error" if applicable).
    */
    private void updateCurrentSemester(String newSemester) {
        currentSemester = newSemester;
        currentSemesterLabel.setText(newSemester != null ? newSemester : "N/A");

        boolean validSemester = (currentSemester != null && !"None".equals(currentSemester) && !"Error".equals(currentSemester));

        // Enable/disable controls based on whether a valid semester is selected
        setAdminControlsEnabled(validSemester);
        setStudentControlsEnabled(validSemester);


        if (validSemester) {
            // Refresh course lists and potentially other semester-dependent data
            rebuildCourseComboBoxes();
            // Clear the display table when semester changes
            clearDisplayTable();
            studentScheduleStatusLabel.setText(" "); // Clear student status
            adminStatusLabel.setText(" "); // Clear admin status
        } else {
            // Clear course combo boxes if semester is invalid
             DefaultComboBoxModel<String> emptyModel = new DefaultComboBoxModel<>();
             addClassCourseComboBox.setModel(emptyModel); // Course list for adding classes is global, leave it? Maybe clear? FIXED: Clear it for consistency.
             studentSelectClassComboBox.setModel(emptyModel);
             adminClassComboBox.setModel(emptyModel);
             clearDisplayTable();
             studentScheduleStatusLabel.setText("Select a valid semester.");
             adminStatusLabel.setText("Select a valid semester.");
        }
    }

    /**
     * Enables or disables admin controls that depend on a valid semester.
     * @param enabled True to enable, false to disable.
     */
    private void setAdminControlsEnabled(boolean enabled) {
        // Add Class tab components (depend on semester)
        // addClassCourseComboBox is global list, but adding a class requires semester context.
        addClassCourseComboBox.setEnabled(enabled);
        seatsTextField.setEnabled(enabled);
        addClassButton.setEnabled(enabled);

        // Admin control panel components (depend on semester)
        adminClassComboBox.setEnabled(enabled);
        adminDisplayStudentsButton.setEnabled(enabled);
        adminDropClassButton.setEnabled(enabled);

        // Dropping a student might be independent of semester, but viewing/dropping classes isn't.
        // Keep adminStudentComboBox enabled if students exist (handled by rebuildStudentComboBoxes)
        // but disable actions requiring semester context.
        adminDropStudentButton.setEnabled(enabled); // Enable based on semester context too, as it removes schedule entries.
    }

    /**
     * Enables or disables student controls that depend on a valid semester.
     * Also considers if students actually exist.
     * @param enabled True to enable based on semester status, false to disable.
     */
    private void setStudentControlsEnabled(boolean enabled) {
        // Student selection itself should be enabled if students exist (handled in rebuildStudentComboBoxes)
        // studentSelectStudentComboBox.setEnabled(enabled);

        // These depend on both a valid semester AND students existing
        boolean studentsExist = studentSelectStudentComboBox.getItemCount() > 0 &&
                               ! "No students found - add students first".equals(studentSelectStudentComboBox.getItemAt(0));

        boolean allowActions = enabled && studentsExist;

        studentSelectClassComboBox.setEnabled(allowActions);
        scheduleButton.setEnabled(allowActions);
        displayScheduleButton.setEnabled(allowActions);
        displayClassesButton.setEnabled(enabled); // Displaying all classes only needs a valid semester
        studentDropClassButton.setEnabled(allowActions);
    }

    /**
     * Clears the main display table and sets default headers.
     */
    private void clearDisplayTable() {
         displayTable.setModel(new DefaultTableModel(new Object[][]{}, SCHEDULE_TABLE_HEADERS)); // Default to schedule headers
    }

    /**
     * Updates the main display table with new data and headers.
     * Should be called from the EDT (e.g., in SwingWorker's done() method).
     *
     * @param data    The 2D data array (or List<List<Object>>).
     * @param headers The column headers.
     */
    private void updateDisplayTable(List<List<Object>> data, String[] headers) {
        // Convert List<List<Object>> to Object[][] for DefaultTableModel
        Object[][] dataArray = data.stream()
                                   .map(List::toArray)
                                   .toArray(Object[][]::new);
        DefaultTableModel model = new DefaultTableModel(dataArray, headers);
        displayTable.setModel(model);
    }


    // --- Event Handlers ---

    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void aboutButtonActionPerformed() {
         JOptionPane.showMessageDialog(this, // Parent component
                  "Author: " + author + "\nProject: " + project,
                  "About Course Scheduler", // Dialog title
                  JOptionPane.INFORMATION_MESSAGE);
    }

    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void changeSemesterButtonActionPerformed() {
         // FIXED: Get selected item correctly
         String selectedSemester = (String) currentSemesterComboBox.getSelectedItem();
         if (selectedSemester != null && !selectedSemester.equals(currentSemester) && !"Loading...".equals(selectedSemester)) {
              updateCurrentSemester(selectedSemester);
         }
    }

    // --- Action Handlers using SwingWorker ---

    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void addSemesterSubmitButtonActionPerformed() {
         // FIXED: Declare local variable 'semester' and get text
         String semester = addSemesterTextfield.getText().trim();
         if (semester.isEmpty()) {
              addSemesterStatusLabel.setText("Please enter a semester name.");
              return;
         }

         // Disable button during operation
         addSemesterSubmitButton.setEnabled(false);
         addSemesterStatusLabel.setText("Adding semester...");

         new SwingWorker<Void, Void>() {
             private boolean success = false;
             private String errorMessage = null;

             @Override
             protected Void doInBackground() throws Exception {
                 try {
                     SemesterQueries.addSemester(semester);
                     success = true;
                 } catch (SQLException e) {
                     errorMessage = e.getMessage();
                     // Log the full error
                     System.err.println("SQL Error adding semester:");
                     e.printStackTrace(); // FIXED: Use printStackTrace for details
                     // System.err.println("SQL Error: " + e); // Redundant
                 }
                 return null; // FIXED: Return null from doInBackground
             }

             @Override
             protected void done() {
                 if (success) {
                     addSemesterStatusLabel.setText("Semester " + semester + " added.");
                     addSemesterTextfield.setText(""); // Clear field on success
                     rebuildSemesterComboBoxes(); // Refresh semester list
                 } else {
                     addSemesterStatusLabel.setText("Error adding semester: " + (errorMessage != null ? errorMessage : "Unknown SQL error"));
                 }
                 // Re-enable button
                 addSemesterSubmitButton.setEnabled(true);
             }
         }.execute();
    }

    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void addCourseButtonActionPerformed() {
        // FIXED: Declare local variables and get text
        String courseCode = courseCodeTextField.getText().trim();
        String description = courseDescTextField.getText().trim();

        // Basic Validation
        if (courseCode.isEmpty() || description.isEmpty()) {
            courseStatusLabel.setText("Course Code and Description cannot be empty.");
            return;
        }
        // TODO: Add more specific validation (e.g., course code format)

        addCourseButton.setEnabled(false);
        courseStatusLabel.setText("Adding course " + courseCode + "...");

        new SwingWorker<Void, Void>() {
            boolean success = false;
            String dbError = null;

            @Override
            protected Void doInBackground() throws Exception {
                try {
                    SemesterQueries.addCourse(courseCode, description);
                    success = true;
                } catch (SQLException e) {
                    dbError = e.getMessage();
                    System.err.println("SQL Error adding course:");
                    e.printStackTrace();
                }
                return null;
            }

            @Override
            protected void done() {
                if (success) {
                    courseStatusLabel.setText("Course " + courseCode + " added successfully.");
                    courseCodeTextField.setText("");
                    courseDescTextField.setText("");
                    rebuildCourseComboBoxes(); // Update course lists
                } else {
                    courseStatusLabel.setText("Error adding course: " + (dbError != null ? dbError : "Unknown error"));
                }
                addCourseButton.setEnabled(true);
            }
        }.execute();
    }


    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void addClassButtonActionPerformed() {
        // FIXED: Declare local variables and get selection/text
        String selectedCourse = (String) addClassCourseComboBox.getSelectedItem();
        String seatsStr = seatsTextField.getText().trim();

        if (selectedCourse == null || "Error loading...".equals(selectedCourse) || selectedCourse.isEmpty()) {
             classStatusLabel.setText("Please select a valid course.");
             return;
        }
        if (seatsStr.isEmpty()) {
             classStatusLabel.setText("Please enter the number of seats.");
             return;
        }
        if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
             classStatusLabel.setText("Cannot add class: No valid semester selected.");
             return;
         }


        int seats;
        try {
            seats = Integer.parseInt(seatsStr);
            if (seats <= 0) {
                classStatusLabel.setText("Number of seats must be positive.");
                return;
            }
        } catch (NumberFormatException e) {
            classStatusLabel.setText("Invalid number format for seats.");
            return;
        }

        addClassButton.setEnabled(false);
        classStatusLabel.setText("Adding class " + selectedCourse + "...");

        new SwingWorker<Void, Void>() {
            boolean success = false;
            String dbError = null;

            @Override
            protected Void doInBackground() throws Exception {
                try {
                    // Ensure currentSemester is valid before proceeding (already checked above, but good practice)
                    if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
                       throw new IllegalStateException("No valid semester selected.");
                    }
                    SemesterQueries.addClass(currentSemester, selectedCourse, seats);
                    success = true;
                } catch (SQLException e) {
                    dbError = e.getMessage();
                    System.err.println("SQL Error adding class:");
                    e.printStackTrace();
                } catch (IllegalStateException e) {
                    dbError = e.getMessage(); // Catch the state exception too
                }
                return null;
            }

             @Override
            protected void done() {
                if (success) {
                    classStatusLabel.setText("Class " + selectedCourse + " added for " + currentSemester + ".");
                    seatsTextField.setText(""); // Clear seats field
                    rebuildCourseComboBoxes(); // Refresh semester-specific course lists in other panels
                } else {
                    classStatusLabel.setText("Error adding class: " + (dbError != null ? dbError : "Unknown error"));
                }
                addClassButton.setEnabled(true);
            }
        }.execute();
    }

     // FIXED: Removed duplicate handler with ActionEvent parameter
     private void addStudentButtonActionPerformed() {
         // FIXED: Declare local variables and get text
         String studentId = studentIdTextField.getText().trim();
         String firstName = firstNameTextField.getText().trim();
         String lastName = lastNameTextField.getText().trim();

         if (studentId.isEmpty() || firstName.isEmpty() || lastName.isEmpty()) {
             studentStatusLabel.setText("Student ID, First Name, and Last Name cannot be empty.");
             return;
         }
         // TODO: Add validation for student ID format/uniqueness if needed

         addStudentButton.setEnabled(false);
         studentStatusLabel.setText("Adding student " + firstName + " " + lastName + "...");

         new SwingWorker<Void, Void>() {
             boolean success = false;
             String dbError = null;

             @Override
             protected Void doInBackground() throws Exception {
                 try {
                     SemesterQueries.addStudent(studentId, firstName, lastName);
                     success = true;
                 } catch (SQLException e) {
                     // Check for specific errors like duplicate ID if DB constraints exist
                     dbError = e.getMessage();
                     System.err.println("SQL Error adding student:");
                     e.printStackTrace();
                 }
                 return null;
             }

             @Override
             protected void done() {
                 if (success) {
                     studentStatusLabel.setText("Student " + lastName + ", " + firstName + " added.");
                     studentIdTextField.setText("");
                     firstNameTextField.setText("");
                     lastNameTextField.setText("");
                     rebuildStudentComboBoxes(); // Refresh student lists
                 } else {
                     studentStatusLabel.setText("Error adding student: " + (dbError != null ? dbError : "Unknown error"));
                 }
                 addStudentButton.setEnabled(true);
             }
         }.execute();
     }

    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void scheduleClassButtonActionPerformed() {
        // FIXED: Declare local variables and get selections
        String studentSelection = (String) studentSelectStudentComboBox.getSelectedItem();
        String classSelection = (String) studentSelectClassComboBox.getSelectedItem();

        if (studentSelection == null || studentSelection.contains("No students found") || studentSelection.contains("Error loading")) {
            studentScheduleStatusLabel.setText("Please select a valid student.");
            return;
        }
        if (classSelection == null || classSelection.contains("Error loading") || classSelection.isEmpty()) {
            studentScheduleStatusLabel.setText("Please select a valid class.");
            return;
        }
        if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
             studentScheduleStatusLabel.setText("Cannot schedule: No valid semester selected.");
             return;
         }


        // FIXED: Assume SemesterQueries handles parsing the ID from the selection string
        String studentId = SemesterQueries.getStudentIDFromComboBox(studentSelection);
        if (studentId == null) {
             studentScheduleStatusLabel.setText("Could not parse Student ID from selection.");
             return;
        }

        // Disable UI elements during operation
        setStudentControlsEnabled(false); // Disable all student controls temporarily
        studentScheduleStatusLabel.setText("Scheduling " + studentSelection + " for " + classSelection + "...");

        new SwingWorker<String, Void>() {
            String dbError = null;

            @Override
            protected String doInBackground() throws Exception {
                try {
                     // Ensure currentSemester is valid
                     if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
                         throw new IllegalStateException("No valid semester selected.");
                     }
                    // This method returns the status ("scheduled" or "waitlisted") or throws exception
                    return SemesterQueries.scheduleClass(currentSemester, studentId, classSelection);
                } catch (SQLException e) {
                    dbError = e.getMessage(); // Capture specific SQL error (e.g., "Student already scheduled/waitlisted", "Class is full")
                    System.err.println("SQL Error scheduling class:");
                    e.printStackTrace();
                    return null; // Return null on error
                 } catch (IllegalStateException e) {
                    dbError = e.getMessage(); // Capture semester state error
                    return null;
                }
            }

            @Override
            protected void done() {
                try {
                    String status = get(); // Get the status returned by doInBackground
                    if (status != null) {
                        studentScheduleStatusLabel.setText("Student " + studentSelection + " " + status + " for " + classSelection + ".");
                        // Optionally, refresh the student's schedule display immediately
                        // displayScheduleButtonActionPerformed(); // Trigger display schedule action
                    } else {
                        // Use the specific error message if available
                        studentScheduleStatusLabel.setText("Error scheduling class: " + (dbError != null ? dbError : "Unknown error"));
                    }
                } catch (InterruptedException | ExecutionException e) {
                     handleDatabaseError(e, "scheduling class");
                     studentScheduleStatusLabel.setText("Error scheduling class.");
                } finally {
                    // Re-enable controls, ensuring valid semester context
                     boolean validSemester = (currentSemester != null && !"None".equals(currentSemester) && !"Error".equals(currentSemester));
                     setStudentControlsEnabled(validSemester);
                }
            }
        }.execute();
    }


    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void displayScheduleButtonActionPerformed() {
        // FIXED: Declare local variable and get selection
        String studentSelection = (String) studentSelectStudentComboBox.getSelectedItem();

        if (studentSelection == null || studentSelection.contains("No students found") || studentSelection.contains("Error loading")) {
            studentScheduleStatusLabel.setText("Please select a valid student.");
            return;
        }
         if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
             studentScheduleStatusLabel.setText("Cannot display schedule: No valid semester selected.");
             return;
         }

        // FIXED: Assume SemesterQueries handles parsing ID
        String studentId = SemesterQueries.getStudentIDFromComboBox(studentSelection);
        if (studentId == null) {
             studentScheduleStatusLabel.setText("Could not parse Student ID from selection.");
             return;
        }

        studentScheduleStatusLabel.setText("Loading schedule for " + studentSelection + "...");
        setStudentControlsEnabled(false); // Disable controls during load

        new SwingWorker<List<List<Object>>, Void>() {
             String dbError = null;

             @Override
             protected List<List<Object>> doInBackground() throws Exception {
                 try {
                      // Ensure currentSemester is valid
                      if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
                          throw new IllegalStateException("No valid semester selected.");
                      }
                     return SemesterQueries.getScheduleByStudent(currentSemester, studentId);
                 } catch (SQLException e) {
                     dbError = e.getMessage();
                     System.err.println("SQL Error loading student schedule:");
                     e.printStackTrace();
                     return null;
                 } catch (IllegalStateException e) {
                     dbError = e.getMessage();
                     return null;
                 }
             }

             @Override
             protected void done() {
                 try {
                     List<List<Object>> scheduleData = get();
                     if (scheduleData != null) {
                          updateDisplayTable(scheduleData, SCHEDULE_TABLE_HEADERS);
                          studentScheduleStatusLabel.setText("Displaying schedule for " + studentSelection);
                     } else {
                          studentScheduleStatusLabel.setText("Error loading schedule: " + (dbError != null ? dbError : "Unknown error"));
                          clearDisplayTable();
                     }
                 } catch (InterruptedException | ExecutionException e) {
                     handleDatabaseError(e, "loading student schedule");
                     studentScheduleStatusLabel.setText("Error loading schedule.");
                     clearDisplayTable();
                 } finally {
                      boolean validSemester = (currentSemester != null && !"None".equals(currentSemester) && !"Error".equals(currentSemester));
                      setStudentControlsEnabled(validSemester);
                 }
             }
         }.execute();
    }

    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void displayClassesButtonActionPerformed() {
         if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
             studentScheduleStatusLabel.setText("Cannot display classes: No valid semester selected.");
             return;
         }

        studentScheduleStatusLabel.setText("Loading all classes for " + currentSemester + "...");
        setStudentControlsEnabled(false); // Disable controls during load

        new SwingWorker<List<List<Object>>, Void>() {
             String dbError = null;

             @Override
             protected List<List<Object>> doInBackground() throws Exception {
                 try {
                      // Ensure currentSemester is valid
                      if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
                          throw new IllegalStateException("No valid semester selected.");
                      }
                     return SemesterQueries.getClassesBySemester(currentSemester);
                 } catch (SQLException e) {
                     dbError = e.getMessage();
                     System.err.println("SQL Error loading classes by semester:");
                     e.printStackTrace();
                     return null;
                 } catch (IllegalStateException e) {
                    dbError = e.getMessage();
                    return null;
                 }
             }

             @Override
             protected void done() {
                 try {
                     List<List<Object>> classData = get();
                     if (classData != null) {
                          updateDisplayTable(classData, CLASS_TABLE_HEADERS);
                          studentScheduleStatusLabel.setText("Displaying all classes for " + currentSemester);
                     } else {
                          studentScheduleStatusLabel.setText("Error loading classes: " + (dbError != null ? dbError : "Unknown error"));
                          clearDisplayTable();
                     }
                 } catch (InterruptedException | ExecutionException e) {
                     handleDatabaseError(e, "loading all classes");
                     studentScheduleStatusLabel.setText("Error loading classes.");
                     clearDisplayTable();
                 } finally {
                      boolean validSemester = (currentSemester != null && !"None".equals(currentSemester) && !"Error".equals(currentSemester));
                      setStudentControlsEnabled(validSemester);
                 }
             }
         }.execute();
    }

    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void studentDropClassButtonActionPerformed() {
        // FIXED: Declare local variables and get selections
        String studentSelection = (String) studentSelectStudentComboBox.getSelectedItem();
        String classSelection = (String) studentSelectClassComboBox.getSelectedItem();

        if (studentSelection == null || studentSelection.contains("No students found") || studentSelection.contains("Error loading")) {
            studentScheduleStatusLabel.setText("Please select a valid student.");
            return;
        }
        if (classSelection == null || classSelection.contains("Error loading") || classSelection.isEmpty()) {
            studentScheduleStatusLabel.setText("Please select a valid class to drop.");
            return;
        }
         if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
             studentScheduleStatusLabel.setText("Cannot drop class: No valid semester selected.");
             return;
         }


        // FIXED: Assume SemesterQueries handles parsing ID
        String studentId = SemesterQueries.getStudentIDFromComboBox(studentSelection);
        if (studentId == null) {
             studentScheduleStatusLabel.setText("Could not parse Student ID from selection.");
             return;
        }

        // Confirmation Dialog
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to drop class " + classSelection + " for " + studentSelection + "?",
                "Confirm Drop",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return; // User cancelled
        }

        setStudentControlsEnabled(false);
        studentScheduleStatusLabel.setText("Dropping " + classSelection + " for " + studentSelection + "...");

        new SwingWorker<Void, Void>() {
            String dbError = null;
            boolean success = false;

            @Override
            protected Void doInBackground() throws Exception {
                try {
                     // Ensure currentSemester is valid
                     if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
                         throw new IllegalStateException("No valid semester selected.");
                     }
                    SemesterQueries.studentDropClass(currentSemester, studentId, classSelection);
                    success = true;
                } catch (SQLException e) {
                    dbError = e.getMessage();
                    System.err.println("SQL Error dropping student class:");
                    e.printStackTrace();
                } catch (IllegalStateException e) {
                    dbError = e.getMessage();
                }
                return null;
            }

            @Override
            protected void done() {
                 boolean refreshAttempted = false;
                 try {
                     if (success) {
                         studentScheduleStatusLabel.setText("Class " + classSelection + " dropped for " + studentSelection + ".");
                         // Refresh the student's schedule view
                         // NOTE: Calling another action handler here can be complex. Ensure it handles re-enabling controls correctly.
                         refreshAttempted = true;
                         displayScheduleButtonActionPerformed(); // Trigger refresh
                     } else {
                         studentScheduleStatusLabel.setText("Error dropping class: " + (dbError != null ? dbError : "Unknown error"));
                     }
                 } finally {
                     // Re-enable controls ONLY if a refresh wasn't attempted
                     // (because the refresh action's finally block should handle it)
                     if (!refreshAttempted) {
                         boolean validSemester = (currentSemester != null && !"None".equals(currentSemester) && !"Error".equals(currentSemester));
                         setStudentControlsEnabled(validSemester); // Re-enable based on semester status
                     }
                 }
            }
        }.execute();
    }


    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void adminDisplayStudentsButtonActionPerformed() {
        // FIXED: Declare local variable and get selection
        String selectedClass = (String) adminClassComboBox.getSelectedItem();

        if (selectedClass == null || selectedClass.contains("Error loading") || selectedClass.isEmpty()) {
            adminStatusLabel.setText("Please select a valid class to display students.");
            return;
        }
        if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
             adminStatusLabel.setText("Cannot display students: No valid semester selected.");
             return;
         }


        adminStatusLabel.setText("Loading students for " + selectedClass + "...");
        setAdminControlsEnabled(false); // Disable controls during load

        new SwingWorker<List<List<Object>>, Void>() {
            String dbError = null;

            @Override
            protected List<List<Object>> doInBackground() throws Exception {
                try {
                     // Ensure currentSemester is valid
                     if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
                         throw new IllegalStateException("No valid semester selected.");
                     }
                    return SemesterQueries.getStudentsInClass(currentSemester, selectedClass);
                } catch (SQLException e) {
                    dbError = e.getMessage();
                    System.err.println("SQL Error getting students in class:");
                    e.printStackTrace();
                    return null;
                } catch (IllegalStateException e) {
                    dbError = e.getMessage();
                    return null;
                }
            }

            @Override
            protected void done() {
                try {
                    List<List<Object>> studentData = get();
                    if (studentData != null) {
                        // Display in a JOptionPane for simplicity, or update main table
                        StringBuilder displayText = new StringBuilder("Students in " + selectedClass + " (" + currentSemester + "):\n\n");
                        displayText.append("Scheduled:\n");
                        boolean scheduledFound = false;
                        for (List<Object> row : studentData) {
                            if (row.size() > 1 && "scheduled".equals(row.get(1))) { // Status is at index 1
                                displayText.append("- ").append(row.get(0)).append("\n"); // Name is at index 0
                                scheduledFound = true;
                            }
                        }
                        if (!scheduledFound) displayText.append("(None)\n");

                        displayText.append("\nWaitlisted:\n");
                        boolean waitlistedFound = false;
                         for (List<Object> row : studentData) {
                            if (row.size() > 1 && "waitlisted".equals(row.get(1))) {
                                displayText.append("- ").append(row.get(0)).append("\n");
                                waitlistedFound = true;
                            }
                         }
                         if (!waitlistedFound) displayText.append("(None)\n");

                         JOptionPane.showMessageDialog(MainFrame.this, displayText.toString(), "Students in Class", JOptionPane.INFORMATION_MESSAGE);
                         adminStatusLabel.setText("Displayed students for " + selectedClass);

                         // Optionally update the main table as well
                         // updateDisplayTable(studentData, STUDENT_TABLE_HEADERS); // Use the correct headers

                    } else {
                        adminStatusLabel.setText("Error loading students: " + (dbError != null ? dbError : "Unknown error"));
                    }
                } catch (InterruptedException | ExecutionException e) {
                    handleDatabaseError(e, "loading students in class");
                    adminStatusLabel.setText("Error loading students.");
                } finally {
                     boolean validSemester = (currentSemester != null && !"None".equals(currentSemester) && !"Error".equals(currentSemester));
                     setAdminControlsEnabled(validSemester);
                }
            }
        }.execute();
    }


    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void adminDropClassButtonActionPerformed() {
        // FIXED: Declare local variable and get selection
        String selectedClass = (String) adminClassComboBox.getSelectedItem();

        if (selectedClass == null || selectedClass.contains("Error loading") || selectedClass.isEmpty()) {
            adminStatusLabel.setText("Please select a valid class to drop.");
            return;
        }
        if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
             adminStatusLabel.setText("Cannot drop class: No valid semester selected.");
             return;
         }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to drop class " + selectedClass + "?\n" +
                "This will remove the class and unenroll ALL students (scheduled and waitlisted).",
                "Confirm Drop Class",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        adminStatusLabel.setText("Dropping class " + selectedClass + "...");
        setAdminControlsEnabled(false);

        new SwingWorker<ArrayList<String>, Void>() {
            String dbError = null;

            @Override
            protected ArrayList<String> doInBackground() throws Exception {
                try {
                     // Ensure currentSemester is valid
                     if (currentSemester == null || "None".equals(currentSemester) || "Error".equals(currentSemester)) {
                         throw new IllegalStateException("No valid semester selected.");
                     }
                    // Returns list of dropped students
                    return SemesterQueries.dropClass(currentSemester, selectedClass);
                } catch (SQLException e) {
                    dbError = e.getMessage();
                    System.err.println("SQL Error dropping class:");
                    e.printStackTrace();
                    return null;
                 } catch (IllegalStateException e) {
                    dbError = e.getMessage();
                    return null;
                }
            }

            @Override
            protected void done() {
                try {
                    ArrayList<String> droppedStudents = get();
                    if (droppedStudents != null) {
                        adminStatusLabel.setText("Class " + selectedClass + " dropped successfully.");
                        rebuildCourseComboBoxes(); // Refresh class lists

                        // Display dropped students
                        StringBuilder message = new StringBuilder("Class " + selectedClass + " dropped.\n\nDropped Students:\n");
                        if (droppedStudents.isEmpty()) {
                            message.append("(None)\n");
                        } else {
                            droppedStudents.forEach(s -> message.append("- ").append(s).append("\n"));
                        }
                        JOptionPane.showMessageDialog(MainFrame.this, message.toString(), "Class Dropped", JOptionPane.INFORMATION_MESSAGE);

                        // Clear the main display table as the context might have changed significantly
                        clearDisplayTable();

                    } else {
                        adminStatusLabel.setText("Error dropping class: " + (dbError != null ? dbError : "Unknown error"));
                    }
                } catch (InterruptedException | ExecutionException e) {
                    handleDatabaseError(e, "dropping class");
                    adminStatusLabel.setText("Error dropping class.");
                } finally {
                     boolean validSemester = (currentSemester != null && !"None".equals(currentSemester) && !"Error".equals(currentSemester));
                     setAdminControlsEnabled(validSemester);
                }
            }
        }.execute();
    }


    // FIXED: Removed duplicate handler with ActionEvent parameter
    private void adminDropStudentButtonActionPerformed() {
        // FIXED: Declare local variable and get selection
        String studentSelection = (String) adminStudentComboBox.getSelectedItem();

        if (studentSelection == null || studentSelection.contains("No students found") || studentSelection.contains("Error loading")) {
            adminStatusLabel.setText("Please select a valid student to drop.");
            return;
        }

        // FIXED: Assume SemesterQueries handles parsing ID
        String studentId = SemesterQueries.getStudentIDFromComboBox(studentSelection);
        if (studentId == null) {
             adminStatusLabel.setText("Could not parse Student ID from selection.");
             return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to drop student " + studentSelection + "?\n" +
                "This will remove the student and all their course registrations.",
                "Confirm Drop Student",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        adminStatusLabel.setText("Dropping student " + studentSelection + "...");
        setAdminControlsEnabled(false); // Disable related controls

        new SwingWorker<Void, Void>() {
            String dbError = null;
            boolean success = false;

            @Override
            protected Void doInBackground() throws Exception {
                try {
                    SemesterQueries.dropStudent(studentId);
                    success = true;
                } catch (SQLException e) {
                    dbError = e.getMessage();
                    System.err.println("SQL Error dropping student:");
                    e.printStackTrace();
                }
                return null;
            }

            @Override
            protected void done() {
                 try {
                    if (success) {
                         adminStatusLabel.setText("Student " + studentSelection + " dropped successfully.");
                         rebuildStudentComboBoxes(); // Refresh student lists
                         // Clear student-specific views if necessary
                         clearDisplayTable();
                    } else {
                         adminStatusLabel.setText("Error dropping student: " + (dbError != null ? dbError : "Unknown error"));
                    }
                 } finally {
                     boolean validSemester = (currentSemester != null && !"None".equals(currentSemester) && !"Error".equals(currentSemester));
                     setAdminControlsEnabled(validSemester); // Re-enable controls based on semester status
                     // Ensure student controls are also re-evaluated
                     setStudentControlsEnabled(validSemester);
                 }
            }
        }.execute();
    }


    // --- Utility and Helper Methods ---

    /**
     * Creates a default GridBagConstraints object with common settings.
     * @return A new GridBagConstraints instance.
     */
    private GridBagConstraints createGBC() {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(5, 5, 5, 5); // Padding
        gbc.anchor = GridBagConstraints.EAST; // Default anchor
        return gbc;
    }

     /**
     * Reads author and project data from the configuration file.
     * If the file doesn't exist, prompts the user and creates the file.
     * Tries both the root directory and the src directory.
     */
    private void checkData() {
        boolean configFound = false;
        
        // Try from root directory first
        try (FileReader reader = new FileReader(AUTHOR_FILE);
             BufferedReader breader = new BufferedReader(reader)) {
            
            configFound = true;
            String encodedAuthor = breader.readLine();
            String encodedProject = breader.readLine();

            if (encodedAuthor != null && encodedProject != null) {
                 try {
                     byte[] decodedAuthor = Base64.getDecoder().decode(encodedAuthor);
                     author = new String(decodedAuthor);
                     byte[] decodedProject = Base64.getDecoder().decode(encodedProject);
                     project = new String(decodedProject);
                     System.out.println("Config loaded from: " + AUTHOR_FILE);
                     return;
                 } catch (IllegalArgumentException ex) {
                     System.err.println("Invalid Base64 encoding in config file. Trying src directory...");
                     configFound = false;
                 }
            } else {
                System.err.println("Empty config file. Trying src directory...");
                configFound = false;
            }
        } catch (FileNotFoundException e) {
            // Try src directory next
            System.out.println("Config not found in root. Trying src directory...");
        } catch (IOException e) {
            System.err.println("Error reading config file from root: " + e.getMessage());
            // Continue to try src directory
        }
        
        // Try from src directory if not found or invalid in root
        if (!configFound) {
            try (FileReader reader = new FileReader("src/" + AUTHOR_FILE);
                 BufferedReader breader = new BufferedReader(reader)) {
                
                String encodedAuthor = breader.readLine();
                String encodedProject = breader.readLine();
                
                if (encodedAuthor != null && encodedProject != null) {
                    try {
                        byte[] decodedAuthor = Base64.getDecoder().decode(encodedAuthor);
                        author = new String(decodedAuthor);
                        byte[] decodedProject = Base64.getDecoder().decode(encodedProject);
                        project = new String(decodedProject);
                        System.out.println("Config loaded from: src/" + AUTHOR_FILE);
                        return;
                    } catch (IllegalArgumentException ex) {
                        System.err.println("Invalid Base64 encoding in src config file.");
                        // Will prompt for info below
                    }
                }
            } catch (FileNotFoundException e) {
                // Both files not found, will prompt user
                System.out.println("Configuration file not found in either location. Prompting for info.");
            } catch (IOException e) {
                System.err.println("Error reading config file from src: " + e.getMessage());
                // Will use defaults or prompt
            }
        }
        
        // If we reach here, either file wasn't found or had invalid content
        promptAndSaveAuthorInfo();
    }

    /**
     * Prompts the user for author name and saves it (along with project name)
     * to the configuration file using Base64 encoding.
     */
    private void promptAndSaveAuthorInfo() {
        author = JOptionPane.showInputDialog(this, "Enter your first and last name:", "Author Information", JOptionPane.PLAIN_MESSAGE);
        // Handle case where user cancels input
        if (author == null || author.trim().isEmpty()) {
            author = "Default User"; // Provide a default if cancelled or empty
            System.out.println("Using default author name.");
        }
        project = "Course Scheduler Fall 2024"; // Default project name

        // Write data to the config file
        try (FileWriter writer = new FileWriter(AUTHOR_FILE); // Overwrite if exists
             BufferedWriter bufferedWriter = new BufferedWriter(writer)) {

            String encodedAuthor = Base64.getEncoder().encodeToString(author.getBytes());
            bufferedWriter.write(encodedAuthor);
            bufferedWriter.newLine();

            String encodedProject = Base64.getEncoder().encodeToString(project.getBytes());
            bufferedWriter.write(encodedProject);
            bufferedWriter.newLine(); // Add newline at end
            System.out.println("Author information saved to " + AUTHOR_FILE);

        } catch (IOException ioe) {
            System.err.println("Error writing configuration file: " + ioe.getMessage());
            // FIXED: Use printStackTrace for details
            ioe.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Could not save configuration file.\nError: " + ioe.getMessage(),
                    "File Write Error", JOptionPane.ERROR_MESSAGE);
            // Application can continue with default/entered info, but it won't be saved
        }
    }
    /**
     * Handles database errors, typically from SwingWorker's done() method.
     * Displays an error message to the user and logs the stack trace.
     *
     * @param ex The exception caught (InterruptedException or ExecutionException).
     * @param operationDescription A description of the operation that failed (e.g., "loading semesters").
     */
    private void handleDatabaseError(Exception ex, String operationDescription) {
        String errorMessage = "An error occurred while " + operationDescription + ".";
        Throwable cause = null; // To store the root cause
        String detailedLogMessage = "Error during operation: [" + operationDescription + "]";

        if (ex instanceof ExecutionException) {
            cause = ex.getCause();
            if (cause instanceof SQLException) {
                errorMessage += "\nDatabase Error: " + cause.getMessage();
                detailedLogMessage += " - SQL Exception: " + cause.getMessage();
            } else if (cause != null) {
                errorMessage += "\nError: " + cause.getMessage();
                detailedLogMessage += " - Caused by: " + cause.getClass().getName() + ": " + cause.getMessage();
            } else {
                errorMessage += "\nExecution Error: " + ex.getMessage(); // Should have cause, but fallback
                detailedLogMessage += " - Execution Exception with no specific cause: " + ex.getMessage();
            }
        } else if (ex instanceof InterruptedException) {
            errorMessage += "\nOperation interrupted.";
            detailedLogMessage += " - Operation Interrupted.";
            Thread.currentThread().interrupt(); // Re-interrupt thread
            cause = ex;
        } else {
            // Handle other potential exceptions from get() if necessary
            errorMessage += "\nUnexpected Error: " + ex.getMessage();
            detailedLogMessage += " - Unexpected Exception: " + ex.getClass().getName() + ": " + ex.getMessage();
            cause = ex;
        }

        // Log the detailed error message first
        System.err.println(detailedLogMessage);

        // Log the stack trace of the actual cause if available, otherwise the wrapper exception
        if (cause != null) {
            System.err.println("--- Root Cause Stack Trace ---");
            cause.printStackTrace(System.err); // Print stack trace of the actual cause to standard error
            System.err.println("--- End Root Cause Stack Trace ---");
        } else {
            System.err.println("--- Exception Stack Trace ---");
            ex.printStackTrace(System.err); // Print trace of the wrapper exception if no cause
            System.err.println("--- End Exception Stack Trace ---");
        }

        // Display user-friendly error in a dialog
        JOptionPane.showMessageDialog(this, errorMessage, "Database Operation Failed", JOptionPane.ERROR_MESSAGE);

        // You might want to update a general status label as well
        // e.g., generalStatusLabel.setText("Database error occurred.");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * NOTE: This code is typically generated by a GUI builder (like NetBeans).
     * Manual modifications should be done carefully.
     * The setupCustomComponents() method is used for post-init setup.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel topPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JPanel semesterPanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        currentSemesterLabel = new javax.swing.JLabel();
        currentSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        addSemesterTextfield = new javax.swing.JTextField();
        addSemesterSubmitButton = new javax.swing.JButton();
        addSemesterStatusLabel = new javax.swing.JLabel();
        javax.swing.JPanel jPanel4_placeholder = new javax.swing.JPanel();
        javax.swing.JPanel jPanel6_placeholder = new javax.swing.JPanel();
        javax.swing.JPanel jPanel7_placeholder = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        topPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Scheduler");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.add(jLabel1, java.awt.BorderLayout.NORTH);

        semesterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        semesterPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setText("Current Semester: ");
        semesterPanel.add(jLabel2);

        currentSemesterLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        currentSemesterLabel.setText("           ");
        currentSemesterLabel.setPreferredSize(new java.awt.Dimension(150, 23));
        semesterPanel.add(currentSemesterLabel);

        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loading..." }));
        currentSemesterComboBox.setPreferredSize(new java.awt.Dimension(150, 26)); // Adjusted size
        semesterPanel.add(currentSemesterComboBox);

        changeSemesterButton.setText("Change Semester");
        semesterPanel.add(changeSemesterButton);

        aboutButton.setText("About");
        semesterPanel.add(aboutButton);

        topPanel.add(semesterPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(topPanel, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        // NOTE: Content for jPanel3 (Add Semester) is defined here by GUI builder
        jLabel3.setText("Semester Name:");

        addSemesterTextfield.setColumns(20);

        addSemesterSubmitButton.setText("Submit");

        addSemesterStatusLabel.setText(" "); // Initial empty status

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addSemesterSubmitButton)
                            .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 428, Short.MAX_VALUE))) // Adjust remaining space as needed
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addSemesterSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(addSemesterStatusLabel)
                .addContainerGap(123, Short.MAX_VALUE)) // Adjust remaining space as needed
        );

        jTabbedPane2.addTab("Add Semester", jPanel3);

        // NOTE: These panels are placeholders. Their content is added manually
        // in setupCustomComponents() -> initializeXxxPanel() methods.
        jPanel4_placeholder.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Course - Content Added Dynamically")); // Example border
        javax.swing.GroupLayout jPanel4_placeholderLayout = new javax.swing.GroupLayout(jPanel4_placeholder);
        jPanel4_placeholder.setLayout(jPanel4_placeholderLayout);
        jPanel4_placeholderLayout.setHorizontalGroup(
            jPanel4_placeholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel4_placeholderLayout.setVerticalGroup(
            jPanel4_placeholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Add Course", jPanel4_placeholder);

        jPanel6_placeholder.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Class - Content Added Dynamically")); // Example border
        javax.swing.GroupLayout jPanel6_placeholderLayout = new javax.swing.GroupLayout(jPanel6_placeholder);
        jPanel6_placeholder.setLayout(jPanel6_placeholderLayout);
        jPanel6_placeholderLayout.setHorizontalGroup(
            jPanel6_placeholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel6_placeholderLayout.setVerticalGroup(
            jPanel6_placeholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Add Class", jPanel6_placeholder);

        jPanel7_placeholder.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Student - Content Added Dynamically")); // Example border
        javax.swing.GroupLayout jPanel7_placeholderLayout = new javax.swing.GroupLayout(jPanel7_placeholder);
        jPanel7_placeholder.setLayout(jPanel7_placeholderLayout);
        jPanel7_placeholderLayout.setHorizontalGroup(
            jPanel7_placeholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        jPanel7_placeholderLayout.setVerticalGroup(
            jPanel7_placeholderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Add Student", jPanel7_placeholder);

        // NOTE: jTabbedPane2 is added to the CENTER of jPanel1 by default here.
        // The initializeAdminControls method adds another panel to the SOUTH of jPanel1.
        jPanel1.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Admin", jPanel1);

        // NOTE: jPanel2 is the container for the Student tab.
        // Its content is added manually in setupCustomComponents -> initializeStudentPanel.
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Student View - Content Added Dynamically")); // Example border
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Student", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null); // Center the frame on screen
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - modify only if using GUI builder post-generation
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JButton addSemesterSubmitButton;
    private javax.swing.JTextField addSemesterTextfield;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> currentSemesterComboBox;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables

    // NOTE: The variables for components added manually (like courseCodeTextField,
    // studentSelectStudentComboBox, displayTable, etc.) are declared at the top
    // of the class definition. The variables declared above are only those
    // directly generated and managed by the NetBeans GUI builder in initComponents().
}